// <auto-generated />
using System;
using Exame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exame.Migrations
{
    [DbContext(typeof(BNP_Paribas_DBContext))]
    [Migration("20221006182748_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exame.Models.MovimentoManual", b =>
                {
                    b.Property<decimal>("DatMes")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("DAT_MES");

                    b.Property<decimal>("DatAno")
                        .HasColumnType("numeric(4,0)")
                        .HasColumnName("DAT_ANO");

                    b.Property<decimal>("NumLancamento")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("NUM_LANCAMENTO");

                    b.Property<string>("CodProduto")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO")
                        .IsFixedLength(true);

                    b.Property<string>("CodCosif")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("COD_COSIF")
                        .IsFixedLength(true);

                    b.Property<string>("CodUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COD_USUARIO");

                    b.Property<DateTime>("DatMovimento")
                        .HasColumnType("smalldatetime")
                        .HasColumnName("DAT_MOVIMENTO");

                    b.Property<string>("DesDescricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DES_DESCRICAO");

                    b.Property<decimal>("ValValor")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("VAL_VALOR");

                    b.HasKey("DatMes", "DatAno", "NumLancamento", "CodProduto", "CodCosif");

                    b.HasIndex("CodProduto", "CodCosif");

                    b.ToTable("MOVIMENTO_MANUAL");
                });

            modelBuilder.Entity("Exame.Models.Produto", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO")
                        .IsFixedLength(true);

                    b.Property<string>("DesProduto")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DES_PRODUTO");

                    b.Property<string>("StaStatus")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS")
                        .IsFixedLength(true);

                    b.HasKey("CodProduto");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("Exame.Models.ProdutoCosif", b =>
                {
                    b.Property<string>("CodProduto")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .HasColumnName("COD_PRODUTO")
                        .IsFixedLength(true);

                    b.Property<string>("CodCosif")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("COD_COSIF")
                        .IsFixedLength(true);

                    b.Property<string>("CodClassificacao")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("COD_CLASSIFICACAO")
                        .IsFixedLength(true);

                    b.Property<string>("StaStatus")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STA_STATUS")
                        .IsFixedLength(true);

                    b.HasKey("CodProduto", "CodCosif");

                    b.ToTable("PRODUTO_COSIF");
                });

            modelBuilder.Entity("Exame.Models.MovimentoManual", b =>
                {
                    b.HasOne("Exame.Models.ProdutoCosif", "Cod")
                        .WithMany("MovimentoManuals")
                        .HasForeignKey("CodProduto", "CodCosif")
                        .HasConstraintName("FK__MOVIMENTO_MANUAL__534D60F1")
                        .IsRequired();

                    b.Navigation("Cod");
                });

            modelBuilder.Entity("Exame.Models.ProdutoCosif", b =>
                {
                    b.HasOne("Exame.Models.Produto", "CodProdutoNavigation")
                        .WithMany("ProdutoCosifs")
                        .HasForeignKey("CodProduto")
                        .HasConstraintName("FK__PRODUTO_C__COD_P__3B75D760")
                        .IsRequired();

                    b.Navigation("CodProdutoNavigation");
                });

            modelBuilder.Entity("Exame.Models.Produto", b =>
                {
                    b.Navigation("ProdutoCosifs");
                });

            modelBuilder.Entity("Exame.Models.ProdutoCosif", b =>
                {
                    b.Navigation("MovimentoManuals");
                });
#pragma warning restore 612, 618
        }
    }
}
